swagger: '2.0'
info:
  title: Backend API
  description: API backend handling.
  version: "1.0.0"
host: 127.0.0.1
schemes:
  - http
produces:
  - application/json
  - text/html

tags:
  - name: API
    description: API Backend Resources
paths:
  /:
    get:
      tags:
        - swagger
      operationId: swagger
      responses:
        '200':
          description: return the api documentation
          schema:
            type: file
  /status:
    get:
      tags:
        - status
      summary: status summary
      description: return all api definition
      operationId: get_status
      responses:
        '200':
          description: successful
          schema:
            $ref: '#/definitions/StatusResponse'
  /receive/message:
    post:
      tags:
       - receive
      summary: receive message from google
      operationId: receive_message
      parameters:
        - name: payload
          in: body
          schema:
            type: object
            properties:
              message:
               type: object
               properties:
                attributes:
                  type: object
                  properties:
                   key:
                    type: string
                data:
                  type: string
                  format: base64
                messageId:
                  type: string
                message_id:
                  type: string
                publishTime:
                  type: string
                publish_time:
                  type: string
      responses:
        "201":
          description: Acknowledgment response
          schema:
            $ref: '#/definitions/Response'
        "200":
          description: Acknowledgment response
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'

definitions:
  StatusResponse:
    type: object
    properties:
      ok:
        type: boolean

  Response:
    type: object
    properties:
      status_code:
        type: integer
        format: int32

  Error:
    type: object
    properties:
      error_code:
        type: integer
        format: int32
