swagger: '2.0'
info:
  title: Backend API
  description: API backend handling.
  version: "1.0.0"
host: 127.0.0.1
schemes:
  - http
produces:
  - application/json
  - text/html

tags:
  - name: API
    description: API Backend Resources
paths:
  /:
    get:
      tags:
        - swagger
      operationId: swagger
      responses:
        '200':
          description: return the api documentation
          schema:
            type: file
  /status:
    get:
      tags:
        - status
      summary: status summary
      description: return all api definition
      operationId: get_status
      responses:
        '200':
          description: successful
          schema:
            $ref: '#/definitions/StatusResponse'
  /receive/message:
    post:
      tags:
       - receive
      summary: receive message from google
      operationId: receive_message
      parameters:
        - name: payload
          in: body
          schema:
            type: object
            properties:
              message:
               type: object
               properties:
                attributes:
                  type: object
                  properties:
                   key:
                    type: string
                data:
                  type: string
                  format: base64
                messageId:
                  type: string
                message_id:
                  type: string
                publishTime:
                  type: string
                publish_time:
                  type: string

      responses:
        "201":
          description: Acknowledgment response
          schema:
            $ref: '#/definitions/Response'
        "400":
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'

  /data/{id}:
    get:
      tags:
       - retrieve
      operationId: get_by_id
      summary: Get a data given an id
      description: given a raw id, data will be returned
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        '200':
          description: return data
          schema:
            $ref: '#/definitions/Data'
        '404':
          description: Resource not found
          schema:
            $ref: '#/definitions/Error'
  /data:
    get:
      tags:
       - retrieve
      operationId: get_by_filter
      summary: Get a data given page_size and page_number
      description: return a list of data
      parameters:
        - name: page_number
          in: query
          type: integer
          required: false
        - name: page_size
          in: query
          type: integer
          required: false
      responses:
        '200':
          description: return list of data
          schema:
            $ref: '#/definitions/DataList'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'


definitions:

  Data:
    type: object
    properties:
      id:
        type: integer
      serial:
          type: string
      application:
          type: integer
      time:
          type: string
      type:
          type: string
      device:
          type: string
      v0:
        type: integer
      v1:
        type: number
      v2:
        type: number
      v3:
        type: number
      v4:
        type: number
      v5:
        type: number
      v6:
        type: number
      v7:
        type: number
      v8:
        type: number
      v9:
        type: number
      v10:
        type: number
      v11:
        type: number
      v12:
        type: number
      v13:
        type: number
      v14:
        type: number
      v15:
        type: number
      v16:
        type: number
      v17:
        type: number
      v18:
        type: number
      date_created:
        type: string

  DataList:
    type: object
    properties:
      data_list:
        type: array
        items:
          $ref: '#/definitions/Data'

  StatusResponse:
    type: object
    properties:
      ok:
        type: boolean

  Response:
    type: object
    properties:
      status_code:
        type: integer
        format: int32
      message:
        type: string

  Error:
    type: object
    properties:
      error_code:
        type: integer
        format: int32
      message:
        type: string
